#!/usr/bin/env python3
"""
One crawlable page per hill.

The site had 546 hills and four crawlable pages. Everything about a hill, the
description, the sun times, the forecast, lived behind client-side state where
no search engine could see it, so somebody searching "Ben Nevis cloud base"
found nothing. This turns four lottery tickets into five hundred and fifty.

THE CONTENT IS IN THE HTML, ON PURPOSE

Every number is written into the page at build time rather than fetched. That
is the entire point: a crawler, and anyone with JavaScript off, sees today's
forecast. A small script then refreshes from the hill's JSON on load, so a page
served from any intermediate cache corrects itself within a second.

They are regenerated by the same build that writes everything else, twice a
day, so a hill page cannot drift from the forecast: same data, same pass. If a
build fails they keep the last good forecast rather than breaking, which is the
better failure mode as long as the page says which day it is for. It does.

Pages link to their neighbours, so the set is a connected graph rather than
five hundred orphans a crawler has to be told about one at a time.
"""

import html
import json
import math
from datetime import datetime

SITE = "https://hillweather.co.uk"
NEARBY = 6


def esc(v):
    return html.escape(str(v), quote=True)


def metres(v):
    return "-" if v is None else f"{v:,} m"


def hhmm(iso):
    return iso[11:16] if iso else "-"


def compass(deg):
    if deg is None:
        return ""
    pts = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE",
           "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"]
    return pts[round(deg / 22.5) % 16]


def haversine(a, b, c, d):
    R, rad = 6371.0, math.pi / 180
    dlat, dlon = (c - a) * rad, (d - b) * rad
    h = (math.sin(dlat / 2) ** 2
         + math.cos(a * rad) * math.cos(c * rad) * math.sin(dlon / 2) ** 2)
    return 2 * R * math.asin(math.sqrt(h))


def verdict_class(s):
    if s.get("verdict") == "ABOVE CLOUD":
        return "c-above"
    v = s.get("view_pct") or 0
    return "c-clear" if v >= 75 else "c-edge" if v > 40 else "c-incloud"


SAID = {
    "ABOVE CLOUD": "above the cloud",
    "JUST ABOVE?": "on top of the cloud, or just in it",
    "CLEAR": "clear of the cloud",
    "ON THE EDGE": "in and out of it all day",
    "IN CLOUD": "in cloud all day",
}


def sentence(h, s):
    """The same reasoning the interactive entry gives, in prose."""
    base, top, height = s.get("cloud_base"), s.get("cloud_top"), h["height"]
    if base is None:
        return "There is no low cloud in the profile at all."
    if s.get("verdict") in ("ABOVE CLOUD", "JUST ABOVE?") and top is not None \
            and height > top:
        return (f"The summit stands about {round(height - top)} m above the top "
                f"of the cloud, with the deck filling the ground below.")
    if base > height:
        return (f"Cloud base sits about {round(base - height)} m above the "
                f"summit, so the top should stay under a ceiling rather than in it.")
    return (f"The summit sits about {round(height - base)} m inside the layer.")


def page(h, meta, region_hills, generated):
    """One hill, as a standalone page."""
    days = sorted(h["daily"])
    today = days[0]
    s = h["daily"][today]
    sun = h["sun"].get(today, {})
    name = h["name"]
    slug = h["slug"]
    region = meta["region"]
    label = meta["label"]
    url = f"{SITE}/hill/{region}/{slug}.html"
    pct = s.get("view_pct")
    said = SAID.get(s.get("verdict"), "")
    # %-d is not portable to Windows, so the day number is placed by hand.
    dt = datetime.fromisoformat(today)
    when = f"{dt.strftime('%A')} {dt.day} {dt.strftime('%B')}"

    desc = (h.get("wikipedia") or {}).get("extract") or ""
    summary = (f"{name}, {metres(h['height'])}. {pct}% chance of a view on "
               f"{when}: {said}. Cloud base, sun times and the hour by hour.")

    # Neighbours, so the pages form a graph a crawler can walk.
    near = sorted(
        (x for x in region_hills if x["slug"] != slug),
        key=lambda x: haversine(h["lat"], h["lon"], x["lat"], x["lon"]))[:NEARBY]

    facts = []
    if h.get("lists"):
        facts.append(("Lists", ", ".join(h["lists"])))
    facts.append(("Height", metres(h["height"]) + (
        f" <small>({h['prominence']:,} m of drop)</small>"
        if h.get("prominence") is not None else "")))
    for key, lbl in (("area", "Area"), ("county", "County"),
                     ("grid_ref", "Grid ref"), ("map50", "OS Landranger"),
                     ("feature", "Summit")):
        if h.get(key):
            v = h[key]
            if key == "county" and h.get("country"):
                v = f"{v}, {h['country']}"
            facts.append((lbl, esc(v)))

    rows = "".join(
        f"<div><dt>{esc(k)}</dt><dd>{v}</dd></div>" for k, v in facts)

    sun_rows = "".join(f"<div><dt>{k}</dt><dd>{v}</dd></div>" for k, v in [
        ("Sunrise", f"{hhmm(sun.get('sunrise'))} "
                    f"<small>{compass(sun.get('sunrise_azimuth'))}</small>"),
        ("Sunset", f"{hhmm(sun.get('sunset'))} "
                   f"<small>{compass(sun.get('sunset_azimuth'))}</small>"),
        ("Daylight", f"{sun.get('daylight_hours', '-')} hours"),
    ])

    # The three days, so the page answers "when" as well as "whether".
    outlook = ""
    for d in days:
        ds = h["daily"][d]
        dd = datetime.fromisoformat(d)
        outlook += (
            f'<div class="outlook-day"><div class="outlook-when">'
            f'{dd.strftime("%a")} {dd.day} {dd.strftime("%b")}</div>'
            f'<div class="outlook-pct {verdict_class(ds)}">{ds.get("view_pct")}%</div>'
            f'<div class="outlook-note">{esc(SAID.get(ds.get("verdict"), ""))}</div>'
            f'</div>')

    hours = [x for x in h.get("hours", [])
             if x["t"].startswith(today) and 6 <= int(x["t"][11:13]) <= 20
             and int(x["t"][11:13]) % 2 == 0]
    hourly = "".join(
        f"<tr><td>{x['t'][11:16]}</td>"
        f"<td class=\"{'c-clear' if (x['view_pct'] or 0) >= 75 else 'c-edge' if (x['view_pct'] or 0) > 40 else 'c-incloud'}\">"
        f"{x['view_pct']}%</td>"
        f"<td class=\"soft\">{'none' if x.get('cloud_base') is None else metres(x['cloud_base'])}</td>"
        f"<td>{x.get('temp', '-')}&deg;</td>"
        f"<td class=\"soft\">{x.get('wind', '-')} {compass(x.get('wind_dir'))}</td></tr>"
        for x in hours)

    about = ""
    wiki = ""
    if desc:
        w = h["wikipedia"]
        wiki = (f'<p class="wiki">{esc(desc)}</p>'
                f'<div class="wiki-credit">From '
                f'<a href="{esc(w["url"])}" rel="noopener">Wikipedia</a>, '
                f'<a href="https://creativecommons.org/licenses/by-sa/4.0/" '
                f'rel="noopener">CC BY-SA 4.0</a></div>')
        about = (f'<section class="guide-lede"><h3>About {esc(name)}</h3>'
                 f'{wiki}</section>')

    links = [f'<a href="https://www.openstreetmap.org/?mlat={h["lat"]}'
             f'&amp;mlon={h["lon"]}#map=14/{h["lat"]}/{h["lon"]}" '
             f'rel="noopener">Map</a>']
    if h.get("walkhighlands"):
        links.append(f'<a href="{esc(h["walkhighlands"])}" rel="noopener">'
                     f'Routes on Walkhighlands</a>')
    if h.get("url"):
        links.append(f'<a href="{esc(h["url"])}" rel="noopener">Hill-bagging</a>')

    nearby = " &middot; ".join(
        f'<a href="{esc(x["slug"])}.html">{esc(x["name"])}</a>' for x in near)

    ld = json.dumps({
        "@context": "https://schema.org",
        "@type": "Place",
        "name": name,
        "url": url,
        "description": desc[:300] if desc else summary,
        "geo": {"@type": "GeoCoordinates",
                "latitude": h["lat"], "longitude": h["lon"],
                "elevation": h["height"]},
        "isPartOf": {"@type": "WebSite", "name": "Hill Weather", "url": SITE + "/"},
    }, separators=(",", ":"))

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(name)} weather: will the summit be in cloud? | Hill Weather</title>
<meta name="description" content="{esc(summary)}">
<script>
try {{
  var m = localStorage.getItem('hw.theme');
  if (m === 'dark' || m === 'light') document.documentElement.setAttribute('data-theme', m);
}} catch (e) {{}}
</script>
<link rel="canonical" href="{url}">
<meta name="theme-color" content="#FBF7F0" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#16140F" media="(prefers-color-scheme: dark)">
<meta property="og:type" content="article">
<meta property="og:site_name" content="Hill Weather">
<meta property="og:title" content="{esc(name)}: will the summit be in cloud?">
<meta property="og:description" content="{esc(summary)}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{SITE}/og.png">
<meta property="og:locale" content="en_GB">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(name)}: will the summit be in cloud?">
<meta name="twitter:description" content="{esc(summary)}">
<meta name="twitter:image" content="{SITE}/og.png">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400..700;1,6..72,400..700&amp;display=swap">
<link rel="stylesheet" href="/style.css">
<script type="application/ld+json">{ld}</script>
</head>
<body>

<header class="masthead wrap">
  <div class="masthead-top kicker">
    <span><a href="/">Hill Weather</a> &middot; {esc(label)}</span>
    <span>Free &middot; No accounts &middot; No advertising</span>
  </div>
  <div class="rule-2"></div>
  <div class="masthead-main compact">
    <h1>{esc(name)}</h1>
    <div class="tagline">{esc(h.get("alt") or metres(h["height"]))}</div>
  </div>
  <div class="rule-1"></div>
</header>

<main class="wrap">
  <section class="guide-lede">
    <h2><span class="{verdict_class(s)}" id="hw-pct">{pct}%</span>
      chance of a view, {esc(said)}.</h2>
    <p id="hw-sentence">{esc(sentence(h, s))}</p>
    <p class="soft">Forecast for <strong id="hw-day">{esc(when)}</strong>,
      built {esc(generated[:16].replace("T", " "))} UTC and rebuilt twice a day.
      A high number is close to reliable, a low one is barely better than a
      shrug: <a href="/how-to-read.html#trust">how reliable is this?</a></p>
  </section>

  <div class="rule-2 spaced"></div>

  <section class="outlook" id="hw-outlook">{outlook}</section>

  <div class="rule-2 spaced"></div>

  <section class="guide-cols">
    <div>
      <h3>The hill</h3>
      <dl class="detail-facts">{rows}</dl>
      <div class="links">{" ".join(links)}</div>
    </div>
    <div>
      <h3>Sun</h3>
      <dl class="detail-facts">{sun_rows}</dl>
    </div>
  </section>

  {about}

  <section class="glossary">
    <h3 class="section-head">Hour by hour, {esc(when)}</h3>
    <div class="rule-2"></div>
    <table>
      <tr><th>Hour</th><th>View</th><th>Cloud base</th><th>Temp</th><th>Wind</th></tr>
      {hourly}
    </table>
  </section>

  <section class="guide-lede">
    <h3>Nearby</h3>
    <p class="soft">{nearby}</p>
    <p><a href="/#/{region}/{today}">All {esc(label)} hills for {esc(when)}</a>
      &middot; <a href="/week.html">The week ahead</a>
      &middot; <a href="/how-to-read.html">How to read this</a></p>
  </section>
</main>

<footer class="wrap">
  <div class="footer-inner">
    <div>
      <h5>Before you go</h5>
      A planning aid, not a forecast service. Always read
      <a href="https://www.mwis.org.uk">MWIS</a>, and in winter
      <a href="https://www.sais.gov.uk">SAIS</a> for avalanche risk.
    </div>
    <div>
      <h5>Sources</h5>
      Weather from <a href="https://open-meteo.com">Open-Meteo</a>, UK Met
      Office 2&nbsp;km model. Hill data from the
      <a href="https://www.hill-bagging.co.uk/dobih">Database of British and
      Irish Hills</a> v18.5, CC&nbsp;BY&nbsp;4.0.
    </div>
  </div>
</footer>

<script>
/* The numbers above are written into this page at build time, so a crawler and
   anyone without JavaScript sees the real forecast. This only refreshes them if
   the page came from a cache older than the current build. */
(async function () {{
  try {{
    const d = await (await fetch('/data/{region}/hills/{slug}.json')).json();
    const days = Object.keys(d.daily).sort();
    if (days[0] === '{today}') return;          // page is current
    location.reload();
  }} catch (e) {{}}
}})();
</script>
<script src="/theme.js"></script>
<script src="/analytics.js"></script>
</body>
</html>
"""


def write_pages(out, out_dir):
    """Every hill in one region. Returns the URLs written."""
    region = out["meta"]["region"]
    generated = out["meta"]["generated_utc"]
    d = out_dir / "hill" / region
    d.mkdir(parents=True, exist_ok=True)

    # The summary view each page needs of its neighbours.
    lite = [{"slug": h["slug"], "name": h["name"],
             "lat": h["lat"], "lon": h["lon"]} for h in out["hills"]]

    urls = []
    for h in out["hills"]:
        (d / f"{h['slug']}.html").write_text(
            page(h, out["meta"], lite, generated), encoding="utf-8", newline="\n")
        urls.append(f"{SITE}/hill/{region}/{h['slug']}.html")
    return urls
